spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mygoods
      username: root
      password: 123456
  profiles:
    include: server,mp

logging:
  level:
    com: debug





